"""
Django settings for librarysys project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path  # Import Path for file system path management

# Base directory of the project
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yr_xq&r^!*46c+c3=40ph+obc4)%(d)lt4@1l$+f&jfb(v-9l6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Set to False in production

ALLOWED_HOSTS = []  # Define allowed domains/IPs in production (e.g., ['yourdomain.com'])


# Application definition

INSTALLED_APPS = [  # List of installed apps and Django components
    'django.contrib.admin',            # Admin interface
    'django.contrib.auth',             # Authentication system
    'django.contrib.contenttypes',     # Content type system
    'django.contrib.sessions',         # Session management
    'django.contrib.messages',         # Messaging framework
    'django.contrib.staticfiles',      # Static file handling
    'bookmap',                         # Your custom app for book-related views/models
    'rest_framework',                  # Django REST framework for building APIs
    'rest_framework.authtoken',        # Token authentication support
]

MIDDLEWARE = [  # Middleware are hooks for processing requests/responses
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# URL configuration module
ROOT_URLCONF = 'librarysys.urls'

# Templates configuration for rendering HTML pages
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # You can add custom template directories here
        'APP_DIRS': True,  # Enables auto-discovery of templates inside each app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # Add request to template context
                'django.contrib.auth.context_processors.auth',  # Add auth context
                'django.contrib.messages.context_processors.messages',  # Flash messages context
            ],
        },
    },
]

# WSGI application entry point
WSGI_APPLICATION = 'librarysys.wsgi.application'

# Django REST framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Use token-based authentication
    ],
}


# Database configuration (MySQL in this case)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Using MySQL as the backend
        'NAME': 'bookmap_db',                 # Your DB name
        'USER': 'root',                       # DB username
        'PASSWORD': 'jyothi1977',             # DB password
        'HOST': '127.0.0.1',                  # DB host (localhost)
        'PORT': '3306',                       # Default MySQL port
    }
}


# Password validators to enforce strong passwords
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # Checks similarity with username/email
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # Ensures password has minimum length
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # Prevents use of common passwords
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # Disallows all-numeric passwords
    },
]


# Internationalization settings
LANGUAGE_CODE = 'en-us'  # Default language

TIME_ZONE = 'UTC'  # Time zone

USE_I18N = True  # Enable internationalization

USE_TZ = True  # Enable timezone-aware datetimes


# Static files (CSS, JavaScript, images)
STATIC_URL = 'static/'  # URL prefix for static files


# Default type for primary keys
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Use BigAutoField for model primary keys
